name: Java CD with Gradle

on:
  push:
    branches: [ "main" , "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout to project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application-dev.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > ./application-dev.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Delivery File
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "spring"
          rm: true

      - name: Execute Jar
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            SOURCE_DIR=$(echo $HOME)/spring
            EXECUTABLE_SPRING_JAR_PATH=$(find $SOURCE_DIR -name '*.jar' 2>/dev/null)
            PROCESS_ID=$(ps aux | grep -i 'java -jar' | grep -v grep | tr ' ' '\n' | sed -e '/^$/d' | head -2 | tail -1)
            if [[ -z $PROCESS_ID ]]; then
                echo "Nothing Process Running"
            else
                echo "Another Process Running"
                kill -9 $PROCESS_ID
            fi
            nohup java -jar $EXECUTABLE_SPRING_JAR_PATH --spring.profiles.active=dev > output.log 2>&1 &
            sleep 1